### ISSUE TITLE
Merge braille utils and dotify CLI

### ISSUE THREAD

**Issue by joeha480** [brailleapps/issues#11]
The braille utils CLI and the dotify CLI should be merged into the same application for the following reasons:
- reduce maintenance overhead (dotify already includes all braille utils CLI functionality)
- increase command symmetry and synergy
- increase focus on whole suite of commands

Tasks:
- [x] Merge repos
- [x] Update readme.md
- [x] Merge BasicUI with DotifyCLI
- [x] Update http://brailleapps.github.io/
- [x] Move issues
- [x] Merge on Open Hub
- [x] Update documentation (/docs)
- [x] Review code and eliminate redundancies etc.
- [x] Make a release of braille-utils-cli indicating that the project has been deprecated
- [x] Merge into dotify-cli master
- [x] Write issue for plugin folder depending on current directory
- [x] Remove from travis
- [x] Look for potential problems in the common wiki (and fix)

**Comment by bertfrees** [comment]
Sounds OK to me!
