### ISSUE TITLE
Remove use of xml-apis

### ISSUE THREAD

**Issue by joeha480** [brailleapps/issues#39]
XML-APIs duplicates standard Java APIs and is therefore not compatible with java modules.

**Comment by joeha480** [comment]
@bertfrees do you know why this is a requirement of jing?

**Comment by bertfrees** [comment]
No idea.

**Comment by joeha480** [comment]
I meant that the daisy-libs version of jing has this as a mandatory requirement when all the other requirements are optional. Anyway, I'll try to remove it and we'll see what happens...

**Comment by bertfrees** [comment]
Could be a bug in the build. When the regular JAR is built (with ANT), it doesn't contain the `org.xml.sax.*`, `org.w3c.dom.*` or `javax.xml.*` packages, but it is possible that the maven-bundle-plugin adds them.
